### ISSUE TITLE
Use Authorize.net Akamai Endpoints

### ISSUE THREAD

**Issue by clintecker** [vcatalano/py-authorize#40]
I received an email from Authorize this morning informing us that they will be transitioning to new Akamai fronted API endpoints in June 2016 (~1 year from now).

The email copy is here: https://gist.github.com/clintecker/e28ce856dec1da907d80
The Authorize.net Akamai FAQ: http://www.authorize.net/support/akamaifaqs/?utm_campaign=Akamai%20Initial%20Email%20to%20Developers%20and%20Partners.ht&utm_medium=email&utm_source=Eloqua

The email says that clients can begin using the new endpoints as early as today.

The new endpoints are at:

- https://api2.authorize.net/xml/v1/request.api
- https://api2.authorize.net/soap/v1/Service.asmx
- https://secure2.authorize.net/gateway/transact.dll

**Comment by fredstluka** [comment]
Yeah, we got the same notice from Authorize.net.

Vincent, will you have time soon to update the URLs, test,
and release a new version?

Thanks!
--Fred

**Comment by vcatalano** [comment]
From what I can tell, this should be a simple fix with a change of the URL. It also should not affect the current API so it's not a critical priority. I will take a look at this soon.

**Comment by fredstluka** [comment]
Thanks, Vincent!

Yeah, I agree it looks like a simple URL change.
I also agree it SHOULD work fine even if you don't make a change,
since they say they will redirect the old URLs to the new ones, but 
it would be nice to stay current anyhow.

Thanks again for py-authorize!  We're using it at HelpHOPELive
to accept donations to fundraising campaigns for patients with 
large medical bills.  You are helping us to make the world a better
place.

--Fred

**Comment by eligundry** [comment]
Does anyone know if this got implemented? I just got an email from authorize.net saying that using these URLs are **mandatory as of June 30th, 2016**.

**Comment by vcatalano** [comment]
Thanks for doing this, @eligundry!

**Comment by fredstluka** [comment]
Vincent,

Have you pushed to PyPi?  For me, pip search py-authorize 
shows that 1.2.3.0 is still the latest version.

Thanks!
--Fred

**Comment by vcatalano** [comment]
I just uploaded this change to Pypi.

**Comment by fredstluka** [comment]
Vincent,

Interesting...

For me, this command:
> % pip search py-authorize

still shows:
> Py-Authorize              - A full-featured Python API for Authorize.net's AIM, CIM, ARB and Reporting APIs.
>  INSTALLED: 1.2.3.0 (latest)

but this script:
> http://code.activestate.com/recipes/577708-check-for-package-updates-on-pypi-works-best-in-pi

shows:
> Py-Authorize 1.2.3.0                     1.2.4.0 available

Any idea why?  Is there something more you should do so that pip search picks it up?

Anyhow, thanks!
--Fred

**Comment by vcatalano** [comment]
Hmmm. That's strange. According to Pypi, everything looks fine https://pypi.python.org/pypi?:action=display&name=Py-Authorize&version=1.2.4.0. Also, `pip search py-authorize` doesn't seem to be working properly for me. I'm wondering if it's due to this issue: https://bitbucket.org/pypa/pypi/issues/326/some-packages-not-showing-up-when (notice the comments from a couple days ago).

**Comment by fredstluka** [comment]
Vincent,

Yeah, that bug seems likely to be the cause.  I added this comment:

> Yeah, same problem here. But I get a much more accurate answer from the script I found here:
> 
>     http://code.activestate.com/recipes/577708-check-for-package-updates-on-pypi-works-best-in-pi
> 
> --Fred

Meanwhile, I have now downloaded 1.2.4.0 via the command:

> % pip install -U py-authorize

Looks good!  Thanks!
--Fred

**Comment by fredstluka** [comment]
Vincent,

I added this to my Python tips page and gave you a shout out.  Thanks!
> http://bristle.com/Tips/Python.htm#pip_checking_for_updates

--Fred
